<?php
    session_start();
    if(isset($_SESSION['suid'])) {
        if ($_SESSION['role'] == 'organisateur'){}
        else{
            die('Vous n\'avez pas accès à cette page');
        }
    }
    else{
        die('Vous n\'avez pas accès à cette page');
    }

?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-Event.IO !</title>
    <link rel="stylesheet" href="../css/style.css">
</head>
<body>
<header>
    <div id="main_div">
        <h1>E-Event.IO !</h1>
        <input type="submit" value="S'inscrire">
        <input type="submit" value="Se connecter">
    </div>
    <div class="menu">
        <ol>
            <li class="menu-item" aria-haspopup="true">
                <a id="lienmenu" href="#">Création</a>
                <ol class="sub-menu" aria-label="sub-menu">
                    <li class="menu-item"><a id="lienmenu" href="campagneform.phtml">Création de campagnes</a></li>
                    <li class="menu-item"><a id="lienmenu" href="evenementform.phtml">Création d'événements</a></li>
                </ol>
            </li>
            <li class="menu-item"><a id="lienmenu" href="demande.phtml">Gestion des inscriptions</a></li>
            <li class="menu-item"><a id="lienmenu" href="jurycampagne.phtml">Jury</a></li>
        </ol>
    </div>
</header>
        <?php
            $campagne = $GLOBALS['campagne'];
            var_dump($campagne);
            echo $campagne->getTempsRestant();
            /*if (!($campagne->getTempsRestant()) or $campagne->getTempsRestant() == 0)
                echo 'Il n\'y a pas de campagne actuellement';*/
        ?>
        <div class="form">
            <form method="post">
                <label>Nom</label>
                <input name="NomEvent" type="text"><br>
                <label>Nom de l'organisateur</label>
                <input name="IdOrga" type="text"><br>
                <label>Description</label>
                <textarea name="contenu" type="text"></textarea><br>
                <input name="eventok" value="Valider" type="submit">
            </form>
        </div>
    </body>
</html>