<!DOCTYPE html  >
<html lang  ="fr"  >
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <meta name="description" content="PageAcceuil">
        <link href="../css/style.css" rel="stylesheet" type="text/css" />
        <title>E-Event.IO !</title>
    </head>
    <body>
        <header>
            <a href="../index.php"><img class="logo" src="../images" alt="logo"></a>
            <nav>
                <ul class="nav_links">
                    <li><a href="evenementform.phtml"> Proposer un événement </a> </li>
                    <li><a href="inprogressevenement.phtml"> Événement en cours </a> </li>
                    <li><a href="campagneform.phtml"> Créer une campagne </a> </li>
                </ul>
            </nav>
            <a class="cta" href="login.phtml"><button> Se connecter </button> </a>
            <a class="cta" href="form.phtml"><button> S'inscrire </button> </a>
        </header>
        <div class="form">
            <form action="../A%20jeter/data-processing.php" method="post">
                <label for="sexe">Civilité</label> <br>
                <label>Homme</label>
                <input name="sexe" value="Homme" type="radio"> <br>
                <label>Femme</label>
                <input name="sexe" value="Femme" type="radio"> <br>
                <label>E-mail</label>
                <input name="email" value="email" type="text"> <br>
                <label>Téléphone</label>
                <input name="tel" value="tel" type="text"> <br>
                <label>Pays</label>
                <select name="pays">
                    <option value="France">France</option>
                    <option value="Allemagne">Allemagne</option>
                    <option value="Italie">Italie</option>
                    <option value="Royaume-Uni">Royaume-Uni</option>
                </select> <br>
                <label name="role">Rôle</label>
                <select name="role">
                    <option value="Organisateur">Organisateur</option>
                    <option value="Donateur">Donateur</option>
                    <option value="Administrateur">Administrateur</option>
                    <option value="Jury">Jury</option>
                </select> <br>
                <!-- <label>Conditions générales</label>
                <input name="condition" value="conditions" type="checkbox"> <br> -->
                <label>Bouton de soumission</label>
                <input name="action" value="Valider" type="submit"><br>
            </form>
        </div>
    </body>
</html>
