<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-Event.IO !</title>
    <link rel="stylesheet" href="../css/style.css">
</head>
<body>
<header>
    <div id="main_div">
        <h1>E-Event.IO !</h1>
        <input type="submit" value="S'inscrire">
        <input type="submit" value="Se connecter">
    </div>
    <div class="menu">
        <ol>
            <li class="menu-item" aria-haspopup="true">
                <a id="lienmenu" href="#">Création</a>
                <ol class="sub-menu" aria-label="sub-menu">
                    <li class="menu-item"><a id="lienmenu" href="campagneform.phtml">Création de campagnes</a></li>
                    <li class="menu-item"><a id="lienmenu" href="evenementform.phtml">Création d'événements</a></li>
                </ol>
            </li>
            <li class="menu-item"><a id="lienmenu" href="demande.phtml">Gestion des inscriptions</a></li>
            <li class="menu-item"><a id="lienmenu" href="jurycampagne.phtml">Jury</a></li>
        </ol>
    </div>
</header>
        <div class="form">
            <form method="post">
                <label for="sexe">Civilité</label> <br>
                <label>Homme</label>
                <input name="sexe" value="Homme" type="radio"> <br>
                <label>Femme</label>
                <input name="sexe" value="Femme" type="radio"> <br>
                <label>E-mail</label>
                <input name="email" value="email" type="text"> <br>
                <label>Téléphone</label>
                <input name="tel" value="tel" type="text"> <br>
                <label>Pays</label>
                <select name="pays">
                    <option value="France">France</option>
                    <option value="Allemagne">Allemagne</option>
                    <option value="Italie">Italie</option>
                    <option value="Royaume-Uni">Royaume-Uni</option>
                </select> <br>
                <label name="role">Rôle</label>
                <select name="role">
                    <option value="Organisateur">Organisateur</option>
                    <option value="Donateur">Donateur</option>
                    <option value="Administrateur">Administrateur</option>
                    <option value="Jury">Jury</option>
                </select> <br>
                <label>Bouton de soumission</label>
                <input name="action" value="Valider" type="submit"><br>
            </form>
        </div>
    </body>
</html>
