<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>e-event.io</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <div id="main_div">
            <h1>e-event.io</h1>
            <input type="submit" value="S'inscrire">
            <input type="submit" value="Se connecter">
        </div>

        <nav>
            <ul>
                <li><a href="#">Création</a></li>
                <li><a href="#">Gestion des inscriptions</a></li>
                <li><a href="#">Jury</a></li>
            </ul>
        </nav>
    </header>

    <div>
        <div class="div_campagne">
            <h1>Campagne n°1</h1>
        </div>

        <div class="div_campagne">
            <h1>Campagne n°2</h1>
        </div>

        <div class="div_campagne">
            <h1>Campagne n°3</h1>
        </div>

        <div class="div_campagne">
            <h1>Campagne n°4</h1>
        </div>

        <div class="div_campagne">
            <h1>Campagne n°5</h1>
        </div>

        <div class="div_campagne">
            <h1>Campagne n°6</h1>
        </div>
    </div>
        
    <footer>
        <p>©e-event.io 2022</p>
    </footer>
</body>
</html>
