<!DOCTYPE html>
<html lang="fr" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-Event.IO !</title>
    <link rel="stylesheet" href="../css/style.css">
</head>
<body>
    <header>
        <div id="banner"
                 <img src="../images/violetfond.png"
            <div id="main_div">
                <h1>E-Event.IO !</h1>
                <input type="submit" value="S'inscrire">
                <input type="submit" value="Se connecter">
            </div>
            <div class="menu">
                <ol>
                 <li class="menu-item" aria-haspopup="true">
                        <a id="lienmenu" href="#">Création</a>
                        <ol class="sub-menu" aria-label="sub-menu">
                            <li class="menu-item"><a id="lienmenu" href="campagneform.phtml">Création de campagnes</a></li>
                            <li class="menu-item"><a id="lienmenu" href="evenementform.phtml">Création d'événements</a></li>
                        </ol>
                    </li>
                    <li class="menu-item"><a id="lienmenu" href="demande.phtml">Gestion des inscriptions</a></li>
                    <li class="menu-item"><a id="lienmenu" href="jurycampagne.phtml">Jury</a></li>
                </ol>
            </div>
        </div>
    </header>

        <div>
            <div class="div_campagne">
                <h1><a href="inprogressevenement.phtml">Campagne </a></h1>
            </div>

            <div class="div_campagne">
                <h1><a href="inprogressevenement.phtml">Campagne n°1</a></h1>
            </div>

            <div class="div_campagne">
                <h1><a href="inprogressevenement.phtml">Campagne n°1</a></h1>
            </div>

            <div class="div_campagne">
                <h1><a href="inprogressevenement.phtml">Campagne n°1</a></h1>
            </div>

            <div class="div_campagne">
                <h1><a href="inprogressevenement.phtml">Campagne n°1</a></h1>
            </div>

            <div class="div_campagne">
                <h1><a href="inprogressevenement.phtml">Campagne n°1</a></h1>
            </div>
        </div>
    <footer>
        <p>©e-event.io 2022</p>
    </footer>
</body>
</html>
